[pytest]
DJANGO_SETTINGS_MODULE = albunmania_project.settings
python_files = test_*.py tests.py
testpaths =
    albunmania_app/tests
    django_attachments
norecursedirs =
    venv
addopts = -ra --cov=albunmania_app --cov-report=
