# Generated by Django 6.0.4 on 2026-05-11 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('collector', 'Coleccionista'), ('merchant', 'Comerciante'), ('web_manager', 'Web Manager'), ('admin', 'Administrador')], default='collector', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('avatar_url', models.URLField(blank=True, verbose_name='avatar URL')),
                ('bio_short', models.CharField(blank=True, max_length=280, verbose_name='bio (short)')),
                ('lat_approx', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='approximate latitude')),
                ('lng_approx', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='approximate longitude')),
                ('active_album_id', models.IntegerField(blank=True, help_text='FK to Album once Epic 2 lands.', null=True, verbose_name='active album id')),
                ('whatsapp_optin', models.BooleanField(default=False, verbose_name='WhatsApp opt-in')),
                ('push_optin', models.BooleanField(default=False, verbose_name='push opt-in')),
                ('browser_geo_optin', models.BooleanField(default=False, verbose_name='browser geolocation opt-in')),
                ('whatsapp_e164', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp number (E.164)')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='rating average')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='rating count')),
                ('positive_pct', models.DecimalField(decimal_places=2, default=0, help_text='Reviews with stars >= 4 / rating_count * 100.', max_digits=5, verbose_name='positive reviews %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='business name')),
                ('business_type', models.CharField(blank=True, choices=[('papeleria', 'Papelería'), ('kiosco', 'Kiosco'), ('libreria', 'Librería'), ('distribuidor', 'Distribuidor oficial'), ('otro', 'Otro')], max_length=20, verbose_name='business type')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='address')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Per-weekday opening hours map.', verbose_name='opening hours')),
                ('declared_stock', models.TextField(blank=True, verbose_name='declared stock')),
                ('subscription_status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='inactive', max_length=12, verbose_name='subscription status')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='subscription expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Profile',
                'verbose_name_plural': 'Merchant Profiles',
                'indexes': [models.Index(fields=['subscription_status'], name='albunmania__subscri_38b04f_idx'), models.Index(fields=['lat', 'lng'], name='albunmania__lat_cae878_idx')],
            },
        ),
    ]
