# Generated by Django 6.0.4 on 2026-05-11 17:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0002_role_extend_profile_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('edition_year', models.PositiveSmallIntegerField(verbose_name='edition year')),
                ('total_stickers', models.PositiveIntegerField(default=0, verbose_name='total stickers')),
                ('is_active', models.BooleanField(default=True, help_text='Active albums are exposed in the public catalogue endpoint.', verbose_name='is active')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='launch date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='cover image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-edition_year', 'name'],
                'indexes': [models.Index(fields=['is_active', 'edition_year'], name='albunmania__is_acti_368500_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120, verbose_name='brand name')),
                ('logo_url', models.URLField(verbose_name='logo URL')),
                ('primary_color', models.CharField(help_text='Hex value (e.g. #0b0b10) used for header band, splash background.', max_length=9, verbose_name='primary color')),
                ('secondary_color', models.CharField(help_text='Accent hex used for splash text and call-to-action borders.', max_length=9, verbose_name='secondary color')),
                ('message_text', models.CharField(blank=True, help_text='Short slogan rendered next to the logo on splash and emails.', max_length=140, verbose_name='message text')),
                ('active_from', models.DateTimeField(verbose_name='active from')),
                ('active_until', models.DateTimeField(verbose_name='active until')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='contract amount (COP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['-active_from'],
                'indexes': [models.Index(fields=['active_from', 'active_until'], name='albunmania__active__26da62_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Sticker number as printed in the album. String to allow "00", "I-1", etc.', max_length=8, verbose_name='number')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('team', models.CharField(blank=True, max_length=160, verbose_name='team')),
                ('image_url', models.URLField(blank=True, verbose_name='image URL')),
                ('is_special_edition', models.BooleanField(default=False, verbose_name='is special edition')),
                ('special_tier', models.CharField(blank=True, choices=[('', '—'), ('gold', 'Oro'), ('metallic', 'Metalizado'), ('brand', 'Marca patrocinadora'), ('zero', 'Lámina 00')], default='', max_length=10, verbose_name='special tier')),
                ('market_value_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Indicative resale value in COP. 0 means unknown.', max_digits=12, verbose_name='market value estimate (COP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='albunmania_app.album')),
            ],
            options={
                'verbose_name': 'Sticker',
                'verbose_name_plural': 'Stickers',
                'ordering': ['album', 'number'],
            },
        ),
        migrations.CreateModel(
            name='UserSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='albunmania_app.sticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User sticker',
                'verbose_name_plural': 'User stickers',
            },
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['album', 'is_special_edition'], name='albunmania__album_i_a06110_idx'),
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['album', 'team'], name='albunmania__album_i_9fddcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='sticker',
            constraint=models.UniqueConstraint(fields=('album', 'number'), name='uniq_sticker_per_album_number'),
        ),
        migrations.AddIndex(
            model_name='usersticker',
            index=models.Index(fields=['user', 'sticker'], name='albunmania__user_id_e89e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersticker',
            index=models.Index(fields=['sticker', 'count'], name='albunmania__sticker_93a349_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersticker',
            constraint=models.UniqueConstraint(fields=('user', 'sticker'), name='uniq_user_sticker'),
        ),
    ]
