# Generated by Django 6.0.4 on 2026-05-11 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0003_catalog_inventory_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('swipe', 'Swipe'), ('qr_presencial', 'QR presencial')], max_length=20)),
                ('status', models.CharField(choices=[('mutual', 'Mutual'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='mutual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_event_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('whatsapp_link_a', models.URLField(blank=True)),
                ('whatsapp_link_b', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='albunmania_app.match')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to=settings.AUTH_USER_MODEL)),
                ('sticker_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_likes', to='albunmania_app.sticker')),
                ('sticker_wanted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_in_likes', to='albunmania_app.sticker')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'indexes': [models.Index(fields=['to_user', 'from_user'], name='albunmania__to_user_ccb27f_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user', 'sticker_offered', 'sticker_wanted'), name='uniq_like_quad')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user_a', 'status'], name='albunmania__user_a__b637d1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user_b', 'status'], name='albunmania__user_b__022869_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b', 'channel'), name='uniq_match_pair_channel'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('user_a__lt', models.F('user_b'))), name='match_user_a_lt_user_b'),
        ),
    ]
