# Generated by Django 6.0.4 on 2026-05-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0004_match_like_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeWhatsAppOptIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opted_in', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_optins', to='albunmania_app.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_whatsapp_optins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade WhatsApp opt-in',
                'verbose_name_plural': 'Trade WhatsApp opt-ins',
                'constraints': [models.UniqueConstraint(fields=('trade', 'user'), name='uniq_trade_whatsapp_optin')],
            },
        ),
    ]
