# Generated by Django 6.0.4 on 2026-05-11 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0005_trade_whatsapp_optin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=200, verbose_name='advertiser name')),
                ('impressions_purchased', models.PositiveIntegerField(verbose_name='impressions purchased')),
                ('impressions_served', models.PositiveIntegerField(default=0, verbose_name='impressions served')),
                ('cpm_rate_cop', models.DecimalField(decimal_places=2, default=0, help_text='Price per 1.000 impressions in Colombian pesos.', max_digits=12, verbose_name='CPM rate (COP)')),
                ('geo_targeting_cities', models.CharField(blank=True, max_length=500, verbose_name='geo targeting cities (csv)')),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Higher weight = served more often vs. peers.', verbose_name='rotation weight')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad campaign',
                'verbose_name_plural': 'Ad campaigns',
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='image URL')),
                ('headline', models.CharField(blank=True, max_length=120, verbose_name='headline')),
                ('body', models.CharField(blank=True, max_length=240, verbose_name='body')),
                ('click_url', models.URLField(verbose_name='click URL')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='rotation weight')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='albunmania_app.adcampaign')),
            ],
            options={
                'verbose_name': 'Ad creative',
                'verbose_name_plural': 'Ad creatives',
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('home', 'Home'), ('feed', 'Feed')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('served_at', models.DateTimeField(auto_now_add=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='albunmania_app.adcreative')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad impression',
                'verbose_name_plural': 'Ad impressions',
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('impression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='albunmania_app.adimpression')),
            ],
            options={
                'verbose_name': 'Ad click',
                'verbose_name_plural': 'Ad clicks',
            },
        ),
        migrations.CreateModel(
            name='MerchantSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cop', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount (COP)')),
                ('period_months', models.PositiveSmallIntegerField(default=1, help_text='Number of months added to subscription_expires_at.', verbose_name='period (months)')),
                ('method', models.CharField(help_text="e.g. 'nequi', 'transferencia', 'efectivo'.", max_length=40, verbose_name='payment method')),
                ('reference', models.CharField(blank=True, help_text='Optional bank/Nequi reference id for reconciliation.', max_length=120, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('paid_at', models.DateTimeField(verbose_name='paid at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='albunmania_app.merchantprofile')),
                ('registered_by', models.ForeignKey(help_text='Web Manager who registered the payment.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant subscription payment',
                'verbose_name_plural': 'Merchant subscription payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='albunmania__status_0c5b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['campaign', 'is_active'], name='albunmania__campaig_a6a766_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['creative', '-served_at'], name='albunmania__creativ_a84077_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['slot', 'city'], name='albunmania__slot_c9d598_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['impression', '-clicked_at'], name='albunmania__impress_e04321_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantsubscriptionpayment',
            index=models.Index(fields=['merchant', '-paid_at'], name='albunmania__merchan_772b30_idx'),
        ),
    ]
