# Generated by Django 6.0.4 on 2026-05-12 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0007_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='p256dh key')),
                ('auth', models.CharField(max_length=64, verbose_name='auth secret')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user-agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push subscription',
                'verbose_name_plural': 'Push subscriptions',
                'indexes': [models.Index(fields=['user', '-last_used_at'], name='albunmania__user_id_8e080a_idx')],
            },
        ),
    ]
