# Generated by Django 6.0.4 on 2026-05-12 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0008_push_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('match_mutual', 'Mutual match'), ('review_received', 'Review received'), ('review_reply', 'Review reply')], max_length=24, verbose_name='kind')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.CharField(blank=True, max_length=400, verbose_name='body')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='deep link')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The other user this notification is about, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='albunmania_app.match')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='albunmania_app.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='albunmania__user_id_c52d5e_idx'), models.Index(fields=['user', '-created_at'], name='albunmania__user_id_a2091e_idx')],
            },
        ),
    ]
