# Generated by Django 6.0.4 on 2026-05-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(choices=[('user', 'User'), ('trade', 'Trade')], max_length=8)),
                ('reason', models.CharField(choices=[('no_show', 'No-show'), ('harassment', 'Harassment / abuse'), ('fake_profile', 'Fake profile'), ('inappropriate', 'Inappropriate content'), ('other', 'Other')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=500, verbose_name='detail')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='albunmania_app.trade')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='albunmania__status_a1de7b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('target_kind', 'user'), ('target_trade__isnull', True), ('target_user__isnull', False)), models.Q(('target_kind', 'trade'), ('target_trade__isnull', False), ('target_user__isnull', True)), _connector='OR'), name='report_target_matches_kind')],
            },
        ),
    ]
