# Generated by Django 6.0.4 on 2026-05-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Updated (throttled) on authenticated activity; drives the Live Badge.', null=True, verbose_name='last seen at'),
        ),
    ]
