# Generated by Django 6.0.4 on 2026-05-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albunmania_app', '0011_profile_last_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordCode',
        ),
    ]
